export const {
    PORT,
    CLOUDINARY_API_KEY,
    CLOUDINARY_API_SECRET,
    CLOUDINARY_CLOUD_NAME,
    DB_URI,
    SMTP_HOST,
    SMTP_PASS,
    SMTP_PORT,
    SMTP_USER,
    REDIS_URI,
    ACCESS_TOKEN_SECRET, ACCESS_TOKEN_EXPIRES,
    NODE_ENV,
    REFRESH_TOKEN_EXPIRES,
    REFRESH_TOKEN_SECRET,
    ACTIVATION_SECRET
} = process.env